apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aap-admin-password-prod
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: aap-admin-password-prod
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: aap
        property: password
