apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aap-admin-password-prod
  namespace: aap
spec:
  encryptedData:
    password: AgReplaceThisWithKubesealOutput
  template:
    metadata:
      name: aap-admin-password-prod
      namespace: aap
    type: Opaque
