apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    vault:
      server: https://vault.example.com
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: aap-eso
          serviceAccountRef:
            name: default
