apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aap
  namespace: openshift-gitops
spec:
  description: Project scope for Ansible Automation Platform 2.6
  sourceRepos:
    - https://github.com/rh-kenelson/argodeployment.git
  destinations:
    - namespace: aap
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
