apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: aap
spec:
  admin_password_secret: aap-admin-password-prod
  image_pull_policy: IfNotPresent
  no_log: true
